Create	Table	X12_999_ErrorMessage(
		ID Int IDENTITY(1,1) PRIMARY KEY,
		Error_ID	varchar(12) Not Null,
		Error_Seq	varchar(8) Not Null,
		Error_Msg	varchar(256) Not Null
)

Create	Index Error_ID On X12_999_ErrorMessage(Error_ID)
Create	Index Error_Seq On X12_999_ErrorMessage(Error_Seq)

Insert Into X12_999_ErrorMessage Select 'AK304','1','Unrecognized segment ID'
Insert Into X12_999_ErrorMessage Select 'AK304','2','Unexpected segment'
Insert Into X12_999_ErrorMessage Select 'AK304','3','Mandatory segment missing'
Insert Into X12_999_ErrorMessage Select 'AK304','4','Loop occurs over maximum times'
Insert Into X12_999_ErrorMessage Select 'AK304','5','Segment exceeds maximum use'
Insert Into X12_999_ErrorMessage Select 'AK304','6','Segment not in defined transaction set'
Insert Into X12_999_ErrorMessage Select 'AK304','7','Segment not in proper sequence'
Insert Into X12_999_ErrorMessage Select 'AK304','8','Segment has data element errors'
Insert Into X12_999_ErrorMessage Select 'AK304','511','Trailing separators encountered (custom code)'

Insert Into X12_999_ErrorMessage Select 'AK403','1','Mandatory data element missing'
Insert Into X12_999_ErrorMessage Select 'AK403','2','Conditional required data element missing'
Insert Into X12_999_ErrorMessage Select 'AK403','3','Too many data elements '
Insert Into X12_999_ErrorMessage Select 'AK403','4','Data element is too short'
Insert Into X12_999_ErrorMessage Select 'AK403','5','Data element is too long'
Insert Into X12_999_ErrorMessage Select 'AK403','6','Invalid character in data element'
Insert Into X12_999_ErrorMessage Select 'AK403','7','Invalid code value'
Insert Into X12_999_ErrorMessage Select 'AK403','8','Invalid date'
Insert Into X12_999_ErrorMessage Select 'AK403','9','Invalid time'
Insert Into X12_999_ErrorMessage Select 'AK403','10','Exclusion condition violated'

Insert Into X12_999_ErrorMessage Select 'AK5','A','Accepted'
Insert Into X12_999_ErrorMessage Select 'AK5','E','Accepted but errors were noted'
Insert Into X12_999_ErrorMessage Select 'AK5','M','Rejected, message authentication code (MAC) failed'
Insert Into X12_999_ErrorMessage Select 'AK5','P','Partially accepted, at least one transaction set was rejected'
Insert Into X12_999_ErrorMessage Select 'AK5','R','Rejected'
Insert Into X12_999_ErrorMessage Select 'AK5','W','Rejected, assurance failed validity tests'
Insert Into X12_999_ErrorMessage Select 'AK5','X','Rejected, content after decryption could not be analyzed'

Insert Into X12_999_ErrorMessage Select 'AK502','1','Transaction set not supported'
Insert Into X12_999_ErrorMessage Select 'AK502','2','Transaction set trailer missing'
Insert Into X12_999_ErrorMessage Select 'AK502','3','Transaction set control number in header and trailer do not match'
Insert Into X12_999_ErrorMessage Select 'AK502','4','Number of included segments does not match actual count'
Insert Into X12_999_ErrorMessage Select 'AK502','5','One or more segments in error'
Insert Into X12_999_ErrorMessage Select 'AK502','6','Missing or invalid transaction set identifier '
Insert Into X12_999_ErrorMessage Select 'AK502','7','Missing or invalid transaction set control number (a duplicate transaction number may have occurred)'

Insert Into X12_999_ErrorMessage Select 'AK9','A','Accepted'
Insert Into X12_999_ErrorMessage Select 'AK9','E','Accepted but errors were noted'
Insert Into X12_999_ErrorMessage Select 'AK9','M','Rejected, message authentication code (MAC) failed'
Insert Into X12_999_ErrorMessage Select 'AK9','P','Partially accepted, at least one transaction set was rejected'
Insert Into X12_999_ErrorMessage Select 'AK9','R','Rejected'
Insert Into X12_999_ErrorMessage Select 'AK9','W','Rejected, assurance failed validity tests'
Insert Into X12_999_ErrorMessage Select 'AK9','X','Rejected, content after decryption could not be analyzed'			

Insert Into X12_999_ErrorMessage Select 'AK905','1','Functional group not supported'
Insert Into X12_999_ErrorMessage Select 'AK905','2','Functional group version not supported'
Insert Into X12_999_ErrorMessage Select 'AK905','3','Functional group trailer missing'
Insert Into X12_999_ErrorMessage Select 'AK905','4','Group control number in the functional group header and trailer do not agree'
Insert Into X12_999_ErrorMessage Select 'AK905','5','Number of included transaction sets does not match actual count'
Insert Into X12_999_ErrorMessage Select 'AK905','6','Group control number violates syntax (a duplicate group control number may have occurred)'

Insert Into X12_999_ErrorMessage Select 'IK3','','Missing segment'

Insert Into X12_999_ErrorMessage Select 'IK304','1','Unrecognized segment ID'
Insert Into X12_999_ErrorMessage Select 'IK304','2','Unexpected segment'
Insert Into X12_999_ErrorMessage Select 'IK304','3','Mandatory segment missing'
Insert Into X12_999_ErrorMessage Select 'IK304','4','Loop occurs over maximum times'
Insert Into X12_999_ErrorMessage Select 'IK304','5','Segment exceeds maximum use'
Insert Into X12_999_ErrorMessage Select 'IK304','6','Segment not in defined transaction set'
Insert Into X12_999_ErrorMessage Select 'IK304','7','Segment not in proper sequence'
Insert Into X12_999_ErrorMessage Select 'IK304','8','Segment has data element errors'
Insert Into X12_999_ErrorMessage Select 'IK304','I4','Implementation "Not Used" Segment Present'
Insert Into X12_999_ErrorMessage Select 'IK304','I6','Implementation Dependent Segment Missing'
Insert Into X12_999_ErrorMessage Select 'IK304','I7','Implementation Loop Occurs Under Minimum Times'
Insert Into X12_999_ErrorMessage Select 'IK304','I8','Implementation Segment Below Minimum Use'
Insert Into X12_999_ErrorMessage Select 'IK304','I9','Implementation Dependent "Not Used" Segment Present'

Insert Into X12_999_ErrorMessage Select 'IK4','','Data Element Note'

Insert Into X12_999_ErrorMessage Select 'IK403','1','Mandatory data element missing'
Insert Into X12_999_ErrorMessage Select 'IK403','2','Conditionally required data element missing'
Insert Into X12_999_ErrorMessage Select 'IK403','3','Too many data elements'
Insert Into X12_999_ErrorMessage Select 'IK403','4','Data element is too short'
Insert Into X12_999_ErrorMessage Select 'IK403','5','Data element too long'
Insert Into X12_999_ErrorMessage Select 'IK403','6','Invalid character in data element'
Insert Into X12_999_ErrorMessage Select 'IK403','7','Invalid code value'
Insert Into X12_999_ErrorMessage Select 'IK403','8','Invalid Date'
Insert Into X12_999_ErrorMessage Select 'IK403','9','Invalid Time'
Insert Into X12_999_ErrorMessage Select 'IK403','10','Exclusion Condition Violated'
Insert Into X12_999_ErrorMessage Select 'IK403','12','Too Many Repetitions'
Insert Into X12_999_ErrorMessage Select 'IK403','13','Too Many Components'
Insert Into X12_999_ErrorMessage Select 'IK403','I6','Code Value Not Used In Implementation'
Insert Into X12_999_ErrorMessage Select 'IK403','I9','Implementation '
Insert Into X12_999_ErrorMessage Select 'IK403','I10','Implementation "Not Used" Data Element Present'
Insert Into X12_999_ErrorMessage Select 'IK403','I11','Implementation Too Few Repetitions'
Insert Into X12_999_ErrorMessage Select 'IK403','I12','Implementation Pattern Match Failure'
Insert Into X12_999_ErrorMessage Select 'IK403','I13','Implementation Dependent "Not Used" Data Element Present'

Insert Into X12_999_ErrorMessage Select 'IK5','A','Accepted'
Insert Into X12_999_ErrorMessage Select 'IK5','E','Accepted but errors were noted'
Insert Into X12_999_ErrorMessage Select 'IK5','M','Rejected, message authentication code (MAC) failed'
Insert Into X12_999_ErrorMessage Select 'IK5','P','Partially accepted, at least one transaction set was rejected'
Insert Into X12_999_ErrorMessage Select 'IK5','R','Rejected'
Insert Into X12_999_ErrorMessage Select 'IK5','W','Rejected, assurance failed validity tests'
Insert Into X12_999_ErrorMessage Select 'IK5','X','Rejected, content after decryption could not be analyzed'

Insert Into X12_999_ErrorMessage Select 'IK504','1','Transaction Set Not Supported'
Insert Into X12_999_ErrorMessage Select 'IK504','2','Transaction Set Trailer Missing'
Insert Into X12_999_ErrorMessage Select 'IK504','3','Transaction Set Control Number in Header and Trailer Do Not Match'
Insert Into X12_999_ErrorMessage Select 'IK504','4','Number of Included Segments Does Not Match Actual Count'
Insert Into X12_999_ErrorMessage Select 'IK504','5','One or More Segments in Error'
Insert Into X12_999_ErrorMessage Select 'IK504','6','Missing or Invalid Transaction Set Identifier'
Insert Into X12_999_ErrorMessage Select 'IK504','7','Missing or Invalid Transaction Set Control Number'
Insert Into X12_999_ErrorMessage Select 'IK504','8','Authentication Key Name Unknown'
Insert Into X12_999_ErrorMessage Select 'IK504','9','Encryption Key Name Unknown'
Insert Into X12_999_ErrorMessage Select 'IK504','10','Requested Service (Authentication or Encrypted) Not Available'
Insert Into X12_999_ErrorMessage Select 'IK504','11','Unknown Security Recipient'
Insert Into X12_999_ErrorMessage Select 'IK504','12','Incorrect Message Length (Encryption Only)'
Insert Into X12_999_ErrorMessage Select 'IK504','13','Message Authentication Code Failed'
Insert Into X12_999_ErrorMessage Select 'IK504','15','Unknown Security Originator'
Insert Into X12_999_ErrorMessage Select 'IK504','16','Syntax Error in Decrypted Text'
Insert Into X12_999_ErrorMessage Select 'IK504','17','Security Not Supported'
Insert Into X12_999_ErrorMessage Select 'IK504','18','Transaction Set not in Functional Group'
Insert Into X12_999_ErrorMessage Select 'IK504','19','Invalid Transaction Set Implementation Convention Reference'
Insert Into X12_999_ErrorMessage Select 'IK504','23','Transaction Set Control Number Not Unique within the Functional Group'
Insert Into X12_999_ErrorMessage Select 'IK504','24','S3E Security End Segment Missing for S3S Security Start Segment'
Insert Into X12_999_ErrorMessage Select 'IK504','25','S3S Security Start Segment Missing for S3E Security End Segment'
Insert Into X12_999_ErrorMessage Select 'IK504','26','S4E Security End Segment Missing for S4S Security Start Segment'
Insert Into X12_999_ErrorMessage Select 'IK504','27','S4S Security Start Segment Missing for S4E Security End Segment'
Insert Into X12_999_ErrorMessage Select 'IK504','I6','Implementation Convention Not Supported'

Insert Into X12_999_ErrorMessage Select 'IK501','A','Accepted'
Insert Into X12_999_ErrorMessage Select 'IK501','E','Accepted but errors were noted'
Insert Into X12_999_ErrorMessage Select 'IK501','M','Rejected, message authentication code (MAC) failed'
Insert Into X12_999_ErrorMessage Select 'IK501','P','Partially accepted, at least one transaction set was rejected'
Insert Into X12_999_ErrorMessage Select 'IK501','R','Rejected'
Insert Into X12_999_ErrorMessage Select 'IK501','W','Rejected, assurance failed validity tests'
Insert Into X12_999_ErrorMessage Select 'IK501','X','Rejected, content after decryption could not be analyzed'
